//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBuyListApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBuyListApplication.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Alcohol {
            get {
                object obj = ResourceManager.GetObject("Alcohol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Animal {
            get {
                object obj = ResourceManager.GetObject("Animal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Automotive {
            get {
                object obj = ResourceManager.GetObject("Automotive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Bookstore {
            get {
                object obj = ResourceManager.GetObject("Bookstore", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Bread {
            get {
                object obj = ResourceManager.GetObject("Bread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/BuyLists.xml.
        /// </summary>
        public static string BuyListsFilePath {
            get {
                return ResourceManager.GetString("BuyListsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Candy {
            get {
                object obj = ResourceManager.GetObject("Candy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Canned {
            get {
                object obj = ResourceManager.GetObject("Canned", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/UserProductCategories.xml.
        /// </summary>
        public static string CategoriesFilePath {
            get {
                return ResourceManager.GetString("CategoriesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Children {
            get {
                object obj = ResourceManager.GetObject("Children", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cleaning {
            get {
                object obj = ResourceManager.GetObject("Cleaning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Clothes {
            get {
                object obj = ResourceManager.GetObject("Clothes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cosmetics {
            get {
                object obj = ResourceManager.GetObject("Cosmetics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Dairy {
            get {
                object obj = ResourceManager.GetObject("Dairy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Dishes {
            get {
                object obj = ResourceManager.GetObject("Dishes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Drinks {
            get {
                object obj = ResourceManager.GetObject("Drinks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Favourite {
            get {
                object obj = ResourceManager.GetObject("Favourite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fish {
            get {
                object obj = ResourceManager.GetObject("Fish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Food {
            get {
                object obj = ResourceManager.GetObject("Food", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Frozen {
            get {
                object obj = ResourceManager.GetObject("Frozen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Fruits {
            get {
                object obj = ResourceManager.GetObject("Fruits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] House {
            get {
                object obj = ResourceManager.GetObject("House", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Meat {
            get {
                object obj = ResourceManager.GetObject("Meat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Office {
            get {
                object obj = ResourceManager.GetObject("Office", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Other {
            get {
                object obj = ResourceManager.GetObject("Other", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Pharmacy {
            get {
                object obj = ResourceManager.GetObject("Pharmacy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ProductCategories&gt;
        ///  &lt;ProductCategory ProductCategoryId=&quot;BREAD&quot; Name=&quot;Pieczywo&quot; Icon=&quot;Bread&quot;/&gt;
        ///  &lt;ProductCategory ProductCategoryId=&quot;FOODSTUFFS&quot; Name=&quot;Jedzenie&quot; Icon=&quot;Food&quot;/&gt;
        ///  &lt;ProductCategory ProductCategoryId=&quot;PHARMACY&quot; Name=&quot;Apteka&quot; Icon=&quot;Pharmacy&quot;/&gt;
        ///  &lt;ProductCategory ProductCategoryId=&quot;OFFICE&quot; Name=&quot;Artykuły biurowe&quot; Icon=&quot;Office&quot;/&gt;
        ///  &lt;ProductCategory ProductCategoryId=&quot;BOOKSTORE&quot; Name=&quot;Ksiażki/Czasopisma&quot; Icon=&quot;Bookstore&quot;/&gt;
        ///  &lt;ProductCategory ProductCat [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;Products&gt;
        ///  &lt;Product ProductId=&quot;BREAD&quot; ProductCategoryId=&quot;BREAD&quot; Name=&quot;Chleb&quot;/&gt;
        ///  &lt;Product ProductId=&quot;ROOLS&quot; ProductCategoryId=&quot;BREAD&quot; Name=&quot;Bułki&quot;/&gt;
        ///  &lt;Product ProductId=&quot;BAGUETTE&quot; ProductCategoryId=&quot;BREAD&quot; Name=&quot;Bagietki&quot;/&gt;
        ///  &lt;Product ProductId=&quot;CRUMBS&quot; ProductCategoryId=&quot;BREAD&quot; Name=&quot;Bułka tarta&quot;/&gt;
        ///  &lt;Product ProductId=&quot;BUN&quot; ProductCategoryId=&quot;BREAD&quot; Name=&quot;Drożdżówki&quot;/&gt;
        ///  &lt;Product ProductId=&quot;PASTA&quot; ProductCategoryId=&quot;FOODSTUFFS&quot; Name=&quot;Makaron&quot;/&gt;
        ///  &lt;Produc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Recreation {
            get {
                object obj = ResourceManager.GetObject("Recreation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Snacks {
            get {
                object obj = ResourceManager.GetObject("Snacks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Spices {
            get {
                object obj = ResourceManager.GetObject("Spices", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
